{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: notification-service
    app.kubernetes.io/name: urbanflow
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: {{ .Values.notificationService.port }}
      targetPort: {{ .Values.notificationService.port }}
{{- end }}
