{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    app.kubernetes.io/name: urbanflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
{{- end }}
