{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
    app.kubernetes.io/name: urbanflow
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
{{- end }}
