apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: urbanflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "urbanflow"
            - name: POSTGRES_USER
              value: "urbanflow_user"
            - name: POSTGRES_PASSWORD
              value: "urbanflow_pass"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - urbanflow_user
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - urbanflow_user
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
