apiVersion: v1
kind: Service
metadata:
  name: mobility-intelligence-service
  namespace: urbanflow
spec:
  selector:
    app: mobility-intelligence-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
