{{- if .Values.incidentReportService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: incident-report-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: incident-report-service
    app.kubernetes.io/name: urbanflow
spec:
  type: ClusterIP
  selector:
    app: incident-report-service
  ports:
    - name: http
      port: {{ .Values.incidentReportService.port }}
      targetPort: {{ .Values.incidentReportService.port }}
{{- end }}
